
const appConstants = {
    API_RESPONSE_SUCCESS: "SUCCESS",
    API_RESPONSE_FAIL: "FAIL",
    API_RESPONSE_STATUS_SUCCESS_CODE: 200,
  
    ACTION_FETCH_NGO_APPROVE_REQ_SUCCESS: "ACTION_FETCH_NGO_APPROVE_REQ_SUCCESS",
    ACTION_FETCH_NGO_APPROVE_REQ_FAIL: "ACTION_FETCH_NGO_APPROVE_REQ_FAIL",
  
    ACTION_FETCH_NGO_PROFILE_SUCCESS: "ACTION_FETCH_NGO_PROFILE_SUCCESS",
    ACTION_FETCH_NGO_PROFILE_FAIL: "ACTION_FETCH_NGO_PROFILE_FAIL",
  
    ACTION_MAP_SEARCH_SUCCESS: "ACTION_MAP_SEARCH_SUCCESS",
    ACTION_MAP_SEARCH_FAIL: "ACTION_MAP_SEARCH_FAIL",
  
    ACTION_GRID_SEARCH_SUCCESS: "ACTION_GRID_SEARCH_SUCCESS",
    ACTION_GRID_SEARCH_FAIL: "ACTION_GRID_SEARCH_FAIL",
    ACTION_UPDATE_LOCATION_SUCCESS: "ACTION_UPDATE_LOCATION_SUCCESS",
  
    ACTION_LOCATION_UPDATE_SUCCESS: "ACTION_LOCATION_UPDATE_SUCCESS",
    ACTION_CSR_REGISTER_SUCCESS: "ACTION_CSR_REGISTER_SUCCESS",
    ACTION_CSR_REGISTER_FAIL: "ACTION_CSR_REGISTER_FAIL",
  
    ACTION_FETCH_ALL_CSR_SUCCESS: "ACTION_FETCH_ALL_CSR_SUCCESS",
    ACTION_FETCH_ALL_CSR_FAIL: "ACTION_FETCH_ALL_CSR_FAIL",
  
    ACTION_FETCH_ALL_SAZENS_SUCCESS: "ACTION_FETCH_ALL_SAZENS_SUCCESS",
    ACTION_FETCH_ALL_SAZENS_FAIL: "ACTION_FETCH_ALL_SAZENS_FAIL",
  
    ACTION_FETCH_ALL_NGOS_SUCCESS: "ACTION_FETCH_ALL_NGOS_SUCCESS",
    ACTION_FETCH_ALL_NGOS_FAIL: "ACTION_FETCH_ALL_NGOS_FAIL",
  
    ACTION_FETCH_ALL_PROMO_CAMPAIGNS_SUCCESS: "ACTION_FETCH_ALL_PROMO_CAMPAIGNS_SUCCESS",
    ACTION_FETCH_ALL_PROMO_CAMPAIGNS_FAIL: "ACTION_FETCH_ALL_PROMO_CAMPAIGNS_FAIL",
  
    ACTION_RESET_ALL_PROMO_CAMPAIGNS: "ACTION_RESET_ALL_PROMO_CAMPAIGNS",
  
    ACTION_FETCH_SUBSCRIPTIONS_SUCCESS: "ACTION_FETCH_SUBSCRIPTIONS_SUCCESS",
    ACTION_FETCH_SUBSCRIPTIONS_FAIL: "ACTION_FETCH_SUBSCRIPTIONS_FAIL",
  
    ACTION_CARD_SELECTED: "ACTION_CARD_SELECTED",
    ACTION_FONT_SIZE_CHANGED: "ACTION_FONT_SIZE_CHANGED",
    ACTION_IMAGE_SIZE_CHANGED: "ACTION_IMAGE_SIZE_CHANGED",
    ACTION_DATE_FORMAT_CHANGED: "ACTION_DATE_FORMAT_CHANGED",
    ACTION_TIME_FORMAT_CHANGED: "ACTION_TIME_FORMAT_CHANGED",
    ACTION_CARD_COLLAPSIBLE: "ACTION_CARD_COLLAPSIBLE",
    ACTION_SHOW_PROGRESS_BAR: "ACTION_SHOW_PROGRESS_BAR",
    ACTION_HIDE_PROGRESS_BAR: "ACTION_HIDE_PROGRESS_BAR",
    ACTION_LOCATION_UPDATE: "ACTION_LOCATION_UPDATE",
  
    ACTION_USER_INFO_SUCCESS: "ACTION_USER_INFO_SUCCESS",
  
    ACTION_FETCH_CSR_APPROVE_REQ_SUCCESS: "ACTION_FETCH_CSR_APPROVE_REQ_SUCCESS",
    ACTION_UPDATE_CSR_APPROVAL_STATUS_SUCCESS:
      "ACTION_UPDATE_CSR_APPROVAL_STATUS_SUCCESS",
    ACTION_UPDATE_CSR_APPROVAL_STATUS_FAIL:
      "ACTION_UPDATE_CSR_APPROVAL_STATUS_FAIL",
    ACTION_FETCH_CSR_PROFILE_SUCCESS: "ACTION_FETCH_CSR_PROFILE_SUCCESS",
    ACTION_FETCH_CSR_PROFILE_FAIL: "ACTION_FETCH_CSR_PROFILE_FAIL",
    ACTION_FETCH_CSR_APPROVE_REQ_FAIL: "ACTION_FETCH_CSR_APPROVE_REQ_FAIL",
  
    sgObjectTypes: {
      EVENT_TYPE_NAME: "event",
      DONATION_TYPE_NAME: "donation",
      VOLUNTEER_TYPE_NAME: "volunteer",
      MEMBERSHIP_TYPE_NAME: "member"
    },
  
    SG_FB_PAGE: 'https://www.facebook.com/SociallyGood-161884181321795/',
    SG_TWITTER_LINK: 'https://twitter.com/GoodSocially',
    SG_YOUTUBE_CHANNEL: 'https://www.youtube.com/channel/UCbIvuZGfhZBUoe7x-4mOEQQ/videos',
    SG_LINKED_IN_PROFILE: 'https://www.linkedin.com/company/sociallygood/',
    SG_INSTAGRAM_PAGE: 'https://www.instagram.com/sociallygoodofficial/',
    SG_BLOG_LINK: 'https://blog.sociallygood.com/'
  };
  
  module.exports = appConstants;
  